---
- hosts: all
  tasks:
    - name: Install the necessary packages
      yum: 
        name: 
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: latest
        update_cache: True
    - name: Install docker-ce.repo
      shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
      args:
        creates: /etc/yum.repos.d/docker-ce.repo
    - name: Install Docker packages
      yum:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: True
    - name: Check the docker version
      shell: "docker --version"
    - name: Create /etc/docker directory
      file:
        path: /etc/docker
        state: directory
    - name: Create a file daemon.json.
      file:
        path: /etc/docker/daemon.json
        state: touch
    - name: Add the configuration on daemon.json file
      copy:
        dest: /etc/docker/daemon.json
        content: |
                  {
                    "exec-opts": ["native.cgroupdriver=systemd"],
                    "log-driver": "json-file",
                    "log-opts": {
                    "max-size": "100m"
                    },
                    "storage-driver": "overlay2",
                    "storage-opts": [
                    "overlay2.override_kernel_check=true"
                    ]
                  }   
    - name: Start the docker service
      service:
        name: docker
        state: started
    - name: Enable docker service
      systemd:
        name: docker.service
        enabled: yes            
