---
- hosts: all
  tasks:
    - name: Change SELinux mode to Permissive
      selinux:
        policy: targeted
        state: permissive
    - name: Print the changes in Configurtion file 
      command: grep SELINUX /etc/sysconfig/selinux
      register: sevalue
    - debug:
        var: sevalue.stdout_lines
    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: "swapoff -a"
    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
    - name: Create a sysctl file k8s.conf.
      file:
        path: /etc/sysctl.d/k8s.conf
        state: touch
    - name: Permanently set required network and swap Linux kernel params on k8s.conf file
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
                 vm.swappiness=0
                 net.bridge.bridge-nf-call-ip6tables = 1
                 net.ipv4.ip_forward = 1
                 net.bridge.bridge-nf-call-iptables = 1
    - name: Apply required network and swap Linux kernel params
      shell: "sysctl --system"
    - name: Add repo file for kubernetes.
      file:
        path: /etc/yum.repos.d/kubernetes.repo
        state: touch
    - name: Add the repository details on kubernetes.repo file
      copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        content: |
                 [kubernetes]
                 name=Kubernetes
                 baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
                 enabled=1
                 gpgcheck=1
                 repo_gpgcheck=1
                 gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
                 exclude=kubelet kubeadm kubectl
    - name: Install Kubernetes packages from repository.
      yum:
        name:
          - kubelet-1.19.4
          - kubeadm-1.19.4
          - kubectl-1.19.4
        state: present
        disable_excludes: all
        exclude: kubernetes
      tags:
       - Install_Kube
    - name: Configure node ip
      shell: echo "KUBELET_EXTRA_ARGS=--node-ip=`ifconfig eth1 | grep 'inet\b' | awk '{ print $2 }'`" > /etc/default/kubelet
      tags:
        - kubelet_file
    - name: Restart kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted
      tags:
        - Restart_kubelet
